Rename kuzzle-reloader to ergol, extract reloader functions, add github action & workflows
kuzzleio/ergol pull request #1
Opened 2021-04-28 14:32 UTC by MathieuVeber

# What does this PR do?

- Rename kuzzle-reloader to ergol
- Extract reloader functions
- Add proper cli options with flags
- Add config file handling
- Adds a linter and ensure that there is no lint errors for each PR.
- Also automates the release on npm when pushing on master.

## Workflows steps

- Pull request: lint test
- Push on master: lint test and (if successful) deployment on NPM

2021-05-05 11:29 UTC, rolljee requested changes

2021-05-05 11:29 UTC, rolljee commented on .github/actions/lint/action.yml
> +    - name: Install deps
Name here does not truly reflect what's happening In there

2021-05-05 11:29 UTC, rolljee commented on .github/workflows/push_master.workflow.yml
> +    needs: [lint]
Add timeout here even if it's a public repository

2021-05-05 11:29 UTC, rolljee commented on .github/workflows/push_master.workflow.yml
> +    steps:
Add timeout here even if it's a public repository

2021-05-05 11:29 UTC, rolljee commented on .github/workflows/pull_request.workflow.yml
> +    name: Lint
Add timeout here even if it's a public repository

2021-05-06 09:39 UTC, alexandrebouthinon approved these changes

2021-05-07 05:52 UTC, rolljee approved these changes

2021-05-07 07:15 UTC, merged